client:
  url: "http://192.168.1.5:3000"

redis:
  host: work-flow-redis
  port: 6379

spring:
  data:
    mongodb:
      uri: mongodb://work-flow-mongodb:27017/work-flow

#logging
logging:
  file:
    name: /var/work-flow/work-flow.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

file-utils:
  image-path: /var/work-flow/image/
