spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        SpringSessionContext: org.springframework.orm.hibernate5.SpringSessionContext
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              MongoOperations: INFO
              MongoDatabaseFactorySupport: INFO
              MongoTemplate.MongoClientSession: INFO
              MongoClient: INFO
              MongoClientImpl: INFO
              Mongo: INFO
              MongoDbFactory: INFO
    mongodb:
      driver: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html

rsa:
  public-key: "-----BEGIN PUBLIC KEY-----MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJiJWaAKg7c+D918vcnuLImPJTmCEa+rxGGXzr/XPcYSHcZag0akfL6ZvISVaL62fyACtEKmFD8SNflqBXd0mlcCAwEAAQ==-----END PUBLIC KEY-----"
  private-key: "MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAmIlZoAqDtz4P3Xy9ye4siY8lOYIRr6vEYZfOv9c9xhIdxlqDRqR8vpm8hJVovrZ/IAK0QqYUPxI1+WoFd3SaVwIDAQABAkEAiI29TIbdL7hBn7jCdvnfqS4a1wbYKnoNDolGr3tTc/L2C0Zdo1fXJsxQw7T60lDEzloeKNG5bqr7Rr+Fb8kvsQIhAMn4GogpLqUQmWHYs4Ry4ipPIkaSXQYZGpa2Kn4S/KllAiEAwVfX3dIQMNsYT6QDD1k1mFa9zGMzxz3VTMl/VphoVwsCIQCMRbm/qcKQuBefYo9DxTqZIf7vPsZG7vaNiBW5HFzJFQIgXNE0+nJr/2hPBXyxU176UcXinApLwyy2B4T8MrA79v0CIQCyfLgRk+35bRA0bRvo3og2xXH5xtlwVlYXW2lURu6f+g=="
