server:
  port: 8080

client:
  url: "http://localhost:3000"

redis:
  host: localhost
  port: 6379

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: work-flow

#logging
logging:
  file:
    name: D:/work-flow/work-flow.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

file-utils:
  image-path: D:/work-flow/image/