client:
  url: "http://192.168.1.5:3000"

redis:
  host: 192.168.1.5
  port: 6379

spring:
  data:
    mongodb:
      host: 192.168.1.5
      port: 27017
      database: work-flow

#logging
logging:
  file:
    name: /var/work-flow/work-flow.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

file-utils:
  image-path: /var/work-flow/image/
