client:
  url: "http://192.168.1.5:3000"

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}

#logging
logging:
  file:
    name: /work-flow/work-flow.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

file-utils:
  image-path: /work-flow/image/
