# docker compose -f docker-compose-dev.yml -p work-flow up -d
services:
  work-flow-db:
    container_name: dev-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=work-flow
    volumes:
      - mongodb-data:/data
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  tomcat:
    container_name: tomcat-server
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_HOST=work-flow-db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=work-flow
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - work-flow-db
      - redis
    networks:
      - app-network

  react-app:
    container_name: react-app-dev
    build:
      context: ./FE
      target: development
      dockerfile: Dockerfile.dev
    volumes:
      - ./FE:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - tomcat
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
