# docker compose -f docker-compose-prod.yml -p work-flow-prod up -d
services:
  work-flow-mongodb:
    container_name: work-flow-mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=work-flow
    volumes:
      - ./mongodb-data:/data
    ports:
      - "27017:27017"
    networks:
      - work-flow-network

  work-flow-redis:
    container_name: work-flow-redis
    image: redis:latest
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - work-flow-network

  work-flow-tomcat:
    container_name: work-flow-tomcat
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - //d/work-flow:/work-flow
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_HOST=work-flow-mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=work-flow
      - REDIS_HOST=work-flow-redis
      - REDIS_PORT=6379
    depends_on:
      - work-flow-mongodb
      - work-flow-redis
    networks:
      - work-flow-network

  work-flow-react:
    container_name: work-flow-react
    build:
      context: ./FE
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - work-flow-tomcat
    networks:
      - work-flow-network

networks:
  work-flow-network:
    driver: bridge
