version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    ports:
      - "9998:9000" # API
      - "9999:9001" # Console
    environment:
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - .D:/minio/data:/data
      - .D:/minio/config:/root/.minio
      - .D:/minio/config:/root/.minio
    command: server --address ":9000" --console-address ":9001" /data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: unless-stopped
