server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: work-flow
  jpa:
    properties:
      hibernate:
        SpringSessionContext: org.springframework.orm.hibernate5.SpringSessionContext
    open-in-view: false

#logging
logging:
  file:
    name: D:/work-flow/work-flow.log
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

springdoc:
  api-docs:
    path: /api-docs
