server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    hikari:
      username: postgres
      password: 1234
      maximum-pool-size: 100
      connection-timeout: 1800000
      max-lifetime: 30000
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    open-in-view: false
    

springdoc:
  api-docs:
    path: /api-docs
