client:
  url: "http://172.24.25.251:3000"

redis:
  host: 172.24.25.251
  port: 6379

spring:
  data:
    mongodb:
      host: 172.24.25.251
      port: 27017
      database: work-flow

#logging
logging:
  file:
    name: /var/work-flow/work-flow.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

file-utils:
  image-path: /var/work-flow/image/
