client:
  url: "http://localhost:3000"

redis:
  host: 192.168.1.4
  port: 6379

spring:
  data:
    mongodb:
      host: 192.168.1.4
      port: 27017
      database: work-flow

s3:
  accessKey: wVxJdDfUf9lzGDY03KKo
  secretKey: dwhUHHvV2kVTvw3iUj8Gc88aOswaZN7JT9v8Q3xC
  minio-endpoint: http://192.168.1.4:9999

#logging
logging:
  file:
    name: D:/work-flow/work-flow.log
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

file-utils:
  image-path: D:/work-flow/image/
